export type Staff = {
  id: number
  name: string
  avatar: string
  sns: Sns
  communities: string[]
  comment: string
}

export interface Sns {
  url: string
  type: "x" | "github"
}

export const staffs: Staff[] = [
  {
    id: 1,
    name: "Gunzi",
    avatar: "https://pbs.twimg.com/profile_images/1321379166332178433/Pqx9MiNH.jpg",
    sns: { url: "https://x.com/com_gunzi", type: "x" },
    communities: [],
    comment: "Gopherくんかわいい",
  },
  {
    id: 2,
    name: "もっちー",
    avatar: "https://avatars.githubusercontent.com/u/43375000",
    sns: { url: "https://github.com/mochi-yu", type: "github" },
    communities: [],
    comment: "各地にコミュニティがあること",
  },
  {
    id: 3,
    name: "nozomuikuta",
    avatar: "https://pbs.twimg.com/profile_images/1326569867101626369/pSyzqRGh_400x400.jpg",
    sns: { url: "https://x.com/nozomuikuta", type: "x" },
    communities: ["newmo, Inc."],
    comment: "ビギナーフレンドリーなところ",
  },
  {
    id: 4,
    name: "luccafort",
    avatar: "https://www.dropbox.com/scl/fi/xfutvvbngfs0rq73df0jz/2023-logo-600x600.png?rlkey=a816mmiqka524c20nevsyxpd5&st=ki1izrxb&raw=1",
    sns: { url: "https://x.com/luccafort", type: "x" },
    communities: ["Kyoto.go"],
    comment: "老若男女、多様性があり、それを大事にしている点。",
  },
  {
    id: 5,
    name: "chihiro",
    avatar: "https://pbs.twimg.com/profile_images/1766876951510384641/mYACvJiR_400x400.jpg",
    sns: { url: "https://x.com/chiroruxxxx", type: "x" },
    communities: ["GoConnect"],
    comment: "年齢関係なくフラットに話せるところ",
  },
  {
    id: 6,
    name: "rayfiyo",
    avatar: "https://raw.githubusercontent.com/rayfiyo/rayfiyo/refs/heads/main/IMG_0212.jpeg",
    sns: { url: "x.com/rayfiyo", type: "x" },
    communities: [],
    comment: "やる気に満ちていて、心温まる人が多くて、業種を問わない受け入れ姿勢が素敵",
  },
  {
    id: 7,
    name: "suu",
    avatar: "https://pbs.twimg.com/profile_images/1460523078593974273/oGIc5NZC_400x400.jpg",
    sns: { url: "https://x.com/suueng", type: "x" },
    communities: ["Women Who Go Tokyo"],
    comment: "間口が広いところ！",
  },
  {
    id: 8,
    name: "convto",
    avatar: "https://avatars.githubusercontent.com/u/23229795",
    sns: { url: "https://x.com/convto", type: "x" },
    communities: [],
    comment: "色々な分野で深掘りしてる人がいるところ！",
  },
  {
    id: 9,
    name: "オーガ",
    avatar: "https://pbs.twimg.com/profile_images/1925932704161284096/F2CCOpr7_400x400.jpg",
    sns: { url: "https://x.com/o_ga09", type: "x" },
    communities: [],
    comment: "Gopherくんが好きな人が多い。可愛いものが好きな人が多い。",
  },
  {
    id: 10,
    name: "sago35",
    avatar: "https://pbs.twimg.com/profile_images/1219630784/profile_400x400.png",
    sns: { url: "https://x.com/sago35tk", type: "x" },
    communities: ["TinyGo Keeb"],
    comment: "Gopher 可愛い",
  },
  {
    id: 11,
    name: "Rinrin",
    avatar: "https://pbs.twimg.com/profile_images/1987812706838249472/y-9XRUaj_400x400.jpg",
    sns: { url: "https://x.com/rin2yh", type: "x" },
    communities: ["株式会社スリーシェイク"],
    comment: "技術力が高くても初心者を温かく迎え入れてくれる雰囲気",
  },
  {
    id: 12,
    name: "kuro",
    avatar: "https://pbs.twimg.com/profile_images/1489962542898495488/kft0Ycs1_400x400.jpg",
    sns: { url: "https://x.com/knkurokuro7", type: "x" },
    communities: [],
    comment: "オープンな雰囲気があるところ",
  },
  {
    id: 13,
    name: "パンダム",
    avatar: "https://pbs.twimg.com/profile_images/1768125639117484032/2EBU8FlI_400x400.jpg",
    sns: { url: "https://x.com/rymiyamoto129", type: "x" },
    communities: [],
    comment: "バイナリ実行！",
  },
  {
    id: 14,
    name: "はせがび",
    avatar: "https://s3.ap-northeast-1.amazonaws.com/wraptas-prod/maropook/266cb8e2-1f3f-80c0-9e08-d90844c4a56b/98c55d300cb14f5526627d475f0b2995.jpg",
    sns: { url: "https://x.com/maropook", type: "x" },
    communities: ["biwako.go"],
    comment: "初心者でも玄人でも楽しんでる",
  },
  {
    id: 15,
    name: "avocadoneko",
    avatar: "https://pbs.twimg.com/profile_images/1847971787231186944/OhuQorXd_400x400.jpg",
    sns: { url: "https://x.com/avocadoneko", type: "x" },
    communities: ["株式会社ビットキー"],
    comment: "コミュニティメンバーがみんな優しいところ！",
  },
  {
    id: 16,
    name: "takamura",
    avatar: "https://avatars.githubusercontent.com/u/51415522?v=4",
    sns: { url: "https://x.com/t4kamura", type: "x" },
    communities: [],
    comment: "Go好きだけでウェルカムなところ",
  },
  {
    id: 17,
    name: "ゆいた",
    avatar: "https://pbs.twimg.com/profile_images/1553350031994126337/EwJvPg17_400x400.jpg",
    sns: { url: "https://x.com/yuita_0360", type: "x" },
    communities: ["株式会社PREVENT"],
    comment: "参加しやすい雰囲気",
  },
  {
    id: 18,
    name: "YNamiki / wancom",
    avatar: "",
    sns: { url: "", type: "" },
    communities: [],
    comment: "初心者にも優しいところ。",
  },
  {
    id: 19,
    name: "masakurapa",
    avatar: "https://avatars.githubusercontent.com/u/31582849",
    sns: { url: "https://x.com/masakurapa", type: "x" },
    communities: ["株式会社カオナビ"],
    comment: "Go Gopher!!",
  },
  {
    id: 20,
    name: "tomtwinkle",
    avatar: "https://avatars.githubusercontent.com/u/47764757",
    sns: { url: "https://x.com/tomtwinklestar", type: "x" },
    communities: ["ANDPAD inc."],
    comment: "良い意味でみんな大人な所",
  },
  {
    id: 21,
    name: "taramanji",
    avatar: "https://taramanji.com/image.png",
    sns: { url: "https://x.com/JavaLangRuntime", type: "x" },
    communities: ["立命館大学大学院", "kyoto.go", "biwako.go"],
    comment: "どこにでも活発なGopherの皆さんがいるところ！",
  },
  {
    id: 22,
    name: "mikichin",
    avatar: "https://pbs.twimg.com/profile_images/1420563286051876866/-q0VIQhE_400x400.jpg",
    sns: { url: "https://x.com/chida_miki", type: "x" },
    communities: ["株式会社メルカリ"],
    comment: "あたたかい雰囲気",
  },
  {
    id: 23,
    name: "佐伯",
    avatar: "https://pbs.twimg.com/profile_images/1793331878277402626/Jv1eJZXT_400x400.jpg",
    sns: { url: "https://x.com/HisafumiSaeki", type: "x" },
    communities: [],
    comment: "",
  },
  {
    id: 24,
    name: "walkure",
    avatar: "http://github.com/walkure.png",
    sns: { url: "http://github.com/walkure/", type: "github" },
    communities: ["マネーフォワード京都"],
    comment: "peaceful & practical",
  },
  {
    id: 25,
    name: "makki_d",
    avatar: "https://pbs.twimg.com/profile_images/999215308/milk_400x400.jpg",
    sns: { url: "https://x.com/makki_d", type: "x" },
    communities: ["KLab株式会社"],
    comment: "プログラミング自体を好きな人が多いところ",
  },
  {
    id: 26,
    name: "tosshy",
    avatar: "https://pbs.twimg.com/profile_images/1910649313086365697/uY1FYF5K_400x400.jpg",
    sns: { url: "https://x.com/mtoshi820", type: "x" },
    communities: [],
    comment: "初心者にもやさしいところ！",
  },
  {
    id: 27,
    name: "tesso",
    avatar: "https://pbs.twimg.com/profile_images/1247018635278741504/MvS-Ij72_400x400.jpg",
    sns: { url: "https://x.com/tesso57", type: "x" },
    communities: [],
    comment: "企業から個人までさまざまな粒度でイベントが開催されているところ",
  },
  {
    id: 28,
    name: "いんてぃ",
    avatar: "https://pbs.twimg.com/profile_images/1933767677723750400/l7_kV-EW_400x400.jpg",
    sns: { url: "https://x.com/intiramisu_", type: "x" },
    communities: ["株式会社野村総合研究所"],
    comment: "若い方々が多く活発なところ",
  },
  {
    id: 29,
    name: "Ras",
    avatar: "https://github.com/ras0q.png",
    sns: { url: "https://x.com/ras0q", type: "x" },
    communities: [],
    comment: "Goが好きな人が集まって議論を深めているところ",
  },
  {
    id: 30,
    name: "hutoboshi",
    avatar: "https://github.com/hutoboshi/myicon/blob/main/myicon.png?raw=true",
    sns: { url: "https://x.com/hutoccho_boshi", type: "x" },
    communities: ["燈株式会社"],
    comment: "みんなGoを愛しているところ",
  },
  {
    id: 31,
    name: "いくら・はむ",
    avatar: "https://avatars.githubusercontent.com/u/104292023",
    sns: { url: "https://x.com/ikura_hamu", type: "x" },
    communities: [],
    comment: "知識の共有が活発",
  },
  {
    id: 32,
    name: "repunit11",
    avatar: "https://pbs.twimg.com/profile_images/1977393762893733888/76EnHgz6_400x400.jpg",
    sns: { url: "https://x.com/repunit11", type: "x" },
    communities: [],
    comment: "",
  },
  {
    id: 33,
    name: "satoken",
    avatar: "https://avatars.githubusercontent.com/u/15720506?v=4",
    sns: { url: "https://x.com/ken5owata", type: "x" },
    communities: ["TinyGo Keeb", "秘密結社オープンフォース"],
    comment: "",
  },
  {
    id: 34,
    name: "n9te9",
    avatar: "https://avatars.githubusercontent.com/u/53435330?s=96&v=4",
    sns: { url: "https://x.com/n9te9", type: "x" },
    communities: [],
    comment: "",
  },
  {
    id: 35,
    name: "りくと",
    avatar: "https://www.rikut0904.site/img/icon.png",
    sns: { url: "https://x.com/rikut0904", type: "x" },
    communities: ["Biwako.go", "Kanazawa.go"],
    comment: "雰囲気がゆったりとしていて居心地がいいところ",
  },
  {
    id: 36,
    name: "Senoue",
    avatar: "https://pbs.twimg.com/profile_images/1951452891304345600/HWCkBlFE_400x400.jpg",
    sns: { url: "https://x.com/senoue", type: "x" },
    communities: ["Sendai.go"],
    comment: "活発",
  },
  {
    id: 37,
    name: "takemio",
    avatar: "https://pbs.twimg.com/profile_images/1375170471595941888/_x5H5bYv_400x400.jpg",
    sns: { url: "https://twitter.com/takemioIO/", type: "x" },
    communities: [],
    comment: "敷居の低さ！",
  },
  {
    id: 38,
    name: "sivchari",
    avatar: "https://avatars.githubusercontent.com/u/55221074?v=4",
    sns: { url: "https://x.com/sivchari", type: "x" },
    communities: ["株式会社LayerX, Go Conferenceメインオーガナイザー, golang.tokyoメインオーガナイザー"],
    comment: "人の温かさ、言語をいろいろな形で盛り上げる人の良さ",
  },
  {
    id: 39,
    name: "OJI",
    avatar: "https://pbs.twimg.com/profile_images/1971174789516754945/Twq2_-gC_400x400.jpg",
    sns: { url: "https://x.com/OldBigBuddha", type: "x" },
    communities: [],
    comment: "",
  },
  {
    id: 40,
    name: "きしだ",
    avatar: "https://pbs.twimg.com/profile_images/1135150231874486272/RmXen0s7_400x400.png",
    sns: { url: "https://x.com/mwudo", type: "x" },
    communities: ["株式会社IVRy"],
    comment: "",
  },
  {
    id: 41,
    name: "turbofish",
    avatar: "https://pbs.twimg.com/profile_images/1970101954119704576/kpE24UGC_400x400.jpg",
    sns: { url: "https://x.com/turbofish_", type: "x" },
    communities: ["NOT A HOTEL"],
    comment: "多様な人が気兼ねなく楽しめる気軽さ＆寛容さ",
  },
  {
    id: 42,
    name: "kyo",
    avatar: "https://pbs.twimg.com/profile_images/1962696053528092672/7ecdBG2f_400x400.jpg",
    sns: { url: "https://x.com/Keyl0ve_", type: "x" },
    communities: ["https://x.com/Keyl0ve_"],
    comment: "Gopher がかわいいので、だいたいのことが許される",
  },
  {
    id: 43,
    name: "micchie",
    avatar: "https://avatars.githubusercontent.com/u/7250468?v=4",
    sns: { url: "https://x.com/micchiebear", type: "x" },
    communities: ["一般社団法人Gophers Japan", "Mercari, Inc."],
    comment: "元気がよろしい！",
  },
  {
    id: 44,
    name: "くりち",
    avatar: "https://pbs.twimg.com/profile_images/1613933979689963521/76Nuikyo_400x400.jpg",
    sns: { url: "https://x.com/kurichi97", type: "x" },
    communities: ["DeckHub株式会社"],
    comment: "",
  },
  {
    id: 45,
    name: "momi",
    avatar: "https://avatars.githubusercontent.com/u/106381541?v=4",
    sns: { url: "https://x.com/irdx_m", type: "x" },
    communities: [],
    comment: "多様な人を受け入れる寛容さと対等に関われる心地良さ🏝️",
  },
  {
    id: 46,
    name: "budougumi0617",
    avatar: "https://pbs.twimg.com/profile_images/680299095727054848/JYTlnxMI_400x400.png",
    sns: { url: "https://x.com/budougumi0617", type: "x" },
    communities: ["株式会社LayerX"],
    comment: "",
  },
  {
    id: 47,
    name: "tak",
    avatar: "https://avatars.githubusercontent.com/u/41906969",
    sns: { url: "https://x.com/tak848_", type: "x" },
    communities: ["株式会社LayerX"],
    comment: "皆Goの推しポイントを語れる",
  },
  {
    id: 48,
    name: "Mikuto",
    avatar: "https://pbs.twimg.com/profile_images/1905930808592044032/lhdu5zOk.jpg",
    sns: { url: "https://x.com/Mikuto_0831", type: "x" },
    communities: ["東京工科大学"],
    comment: "",
  },
  {
    id: 49,
    name: "syamasaw",
    avatar: "https://pbs.twimg.com/profile_images/2047300684278820864/qcqwugnz_400x400.jpg",
    sns: { url: "", type: "" },
    communities: [],
    comment: "",
  },
];
