export type Staff = {
  id: number
  name: string
  avatar: string
  sns: Sns
  communities: string[]
  comment: string
}

export interface Sns {
  url: string
  type: string
}

export const staffs: Staff[] = [
  {
    id: 1,
    name: "Gunzi",
    avatar: "../assets/staff_img/1.jpg",
    sns: { url: "https://x.com/com_gunzi", type: "x" },
    communities: [],
    comment: "Gopherくんかわいい",
  },
  {
    id: 2,
    name: "もっちー",
    avatar: "../assets/staff_img/2.jpg",
    sns: { url: "https://github.com/mochi-yu", type: "github" },
    communities: [],
    comment: "各地にコミュニティがあること",
  },
  {
    id: 3,
    name: "nozomuikuta",
    avatar: "../assets/staff_img/3.jpg",
    sns: { url: "https://x.com/nozomuikuta", type: "x" },
    communities: ["newmo, Inc."],
    comment: "ビギナーフレンドリーなところ",
  },
  {
    id: 4,
    name: "luccafort",
    avatar: "../assets/staff_img/4.png",
    sns: { url: "https://x.com/luccafort", type: "x" },
    communities: ["Kyoto.go"],
    comment: "老若男女、多様性があり、それを大事にしている点。",
  },
  {
    id: 5,
    name: "chihiro",
    avatar: "../assets/staff_img/5.jpg",
    sns: { url: "https://x.com/chiroruxxxx", type: "x" },
    communities: ["GoConnect"],
    comment: "年齢関係なくフラットに話せるところ",
  },
  {
    id: 6,
    name: "rayfiyo",
    avatar: "../assets/staff_img/6.jpg",
    sns: { url: "x.com/rayfiyo", type: "x" },
    communities: [],
    comment: "やる気に満ちていて、心温まる人が多くて、業種を問わない受け入れ姿勢が素敵",
  },
  {
    id: 7,
    name: "suu",
    avatar: "../assets/staff_img/7.jpg",
    sns: { url: "https://x.com/suueng", type: "x" },
    communities: ["Women Who Go Tokyo"],
    comment: "間口が広いところ！",
  },
  {
    id: 8,
    name: "convto",
    avatar: "../assets/staff_img/8.png",
    sns: { url: "https://x.com/convto", type: "x" },
    communities: [],
    comment: "色々な分野で深掘りしてる人がいるところ！",
  },
  {
    id: 9,
    name: "オーガ",
    avatar: "../assets/staff_img/9.jpg",
    sns: { url: "https://x.com/o_ga09", type: "x" },
    communities: [],
    comment: "Gopherくんが好きな人が多い。可愛いものが好きな人が多い。",
  },
  {
    id: 10,
    name: "sago35",
    avatar: "../assets/staff_img/10.png",
    sns: { url: "https://x.com/sago35tk", type: "x" },
    communities: ["TinyGo Keeb"],
    comment: "Gopher 可愛い",
  },
  {
    id: 11,
    name: "Rinrin",
    avatar: "../assets/staff_img/11.jpg",
    sns: { url: "https://x.com/rin2yh", type: "x" },
    communities: ["株式会社スリーシェイク"],
    comment: "技術力が高くても初心者を温かく迎え入れてくれる雰囲気",
  },
  {
    id: 12,
    name: "kuro",
    avatar: "../assets/staff_img/12.jpg",
    sns: { url: "https://x.com/knkurokuro7", type: "x" },
    communities: [],
    comment: "オープンな雰囲気があるところ",
  },
  {
    id: 13,
    name: "パンダム",
    avatar: "https://x.com/rymiyamoto129/photo",
    sns: { url: "https://x.com/rymiyamoto129", type: "x" },
    communities: [],
    comment: "バイナリ実行！",
  },
  {
    id: 14,
    name: "はせがび",
    avatar: "../assets/staff_img/14.jpg",
    sns: { url: "https://x.com/maropook", type: "x" },
    communities: ["biwako.go"],
    comment: "初心者でも玄人でも楽しんでる",
  },
  {
    id: 15,
    name: "avocadoneko",
    avatar: "https://x.com/avocadoneko/photo",
    sns: { url: "https://x.com/avocadoneko", type: "x" },
    communities: ["株式会社ビットキー"],
    comment: "コミュニティメンバーがみんな優しいところ！",
  },
  {
    id: 16,
    name: "takamura",
    avatar: "../assets/staff_img/16.png",
    sns: { url: "https://x.com/t4kamura", type: "x" },
    communities: [],
    comment: "Go好きだけでウェルカムなところ",
  },
  {
    id: 17,
    name: "ゆいた",
    avatar: "../assets/staff_img/17.jpg",
    sns: { url: "https://x.com/yuita_0360", type: "x" },
    communities: ["株式会社PREVENT"],
    comment: "参加しやすい雰囲気",
  },
  {
    id: 18,
    name: "YNamiki / wancom",
    avatar: "",
    sns: { url: "", type: "" },
    communities: [],
    comment: "初心者にも優しいところ。",
  },
  {
    id: 19,
    name: "masakurapa",
    avatar: "../assets/staff_img/19.png",
    sns: { url: "https://x.com/masakurapa", type: "x" },
    communities: ["株式会社カオナビ"],
    comment: "Go Gopher!!",
  },
  {
    id: 20,
    name: "tomtwinkle",
    avatar: "../assets/staff_img/20.png",
    sns: { url: "https://x.com/tomtwinklestar", type: "x" },
    communities: ["ANDPAD inc."],
    comment: "良い意味でみんな大人な所",
  },
  {
    id: 21,
    name: "taramanji",
    avatar: "../assets/staff_img/21.png",
    sns: { url: "https://x.com/JavaLangRuntime", type: "x" },
    communities: ["立命館大学大学院", "kyoto.go", "biwako.go"],
    comment: "どこにでも活発なGopherの皆さんがいるところ！",
  },
  {
    id: 22,
    name: "mikichin",
    avatar: "../assets/staff_img/22.jpg",
    sns: { url: "https://x.com/chida_miki", type: "x" },
    communities: ["株式会社メルカリ"],
    comment: "あたたかい雰囲気",
  },
  {
    id: 23,
    name: "佐伯",
    avatar: "../assets/staff_img/23.jpg",
    sns: { url: "https://x.com/HisafumiSaeki", type: "x" },
    communities: [],
    comment: "",
  },
  {
    id: 24,
    name: "walkure",
    avatar: "../assets/staff_img/24.jpg",
    sns: { url: "http://github.com/walkure/", type: "github" },
    communities: ["マネーフォワード京都"],
    comment: "peaceful & practical",
  },
  {
    id: 25,
    name: "makki_d",
    avatar: "../assets/staff_img/25.jpg",
    sns: { url: "https://x.com/makki_d", type: "x" },
    communities: ["KLab株式会社"],
    comment: "プログラミング自体を好きな人が多いところ",
  },
  {
    id: 26,
    name: "tosshy",
    avatar: "../assets/staff_img/26.jpg",
    sns: { url: "https://x.com/mtoshi820", type: "x" },
    communities: [],
    comment: "初心者にもやさしいところ！",
  },
  {
    id: 27,
    name: "tesso",
    avatar: "../assets/staff_img/27.jpg",
    sns: { url: "https://x.com/tesso57", type: "x" },
    communities: [],
    comment: "企業から個人までさまざまな粒度でイベントが開催されているところ",
  },
  {
    id: 28,
    name: "いんてぃ",
    avatar: "../assets/staff_img/28.jpg",
    sns: { url: "https://x.com/intiramisu_", type: "x" },
    communities: ["株式会社野村総合研究所"],
    comment: "若い方々が多く活発なところ",
  },
  {
    id: 29,
    name: "Ras",
    avatar: "../assets/staff_img/29.png",
    sns: { url: "https://x.com/ras0q", type: "x" },
    communities: [],
    comment: "Goが好きな人が集まって議論を深めているところ",
  },
  {
    id: 30,
    name: "hutoboshi",
    avatar: "../assets/staff_img/30.png",
    sns: { url: "https://x.com/hutoccho_boshi", type: "x" },
    communities: ["燈株式会社"],
    comment: "みんなGoを愛しているところ",
  },
  {
    id: 31,
    name: "いくら・はむ",
    avatar: "../assets/staff_img/31.png",
    sns: { url: "https://x.com/ikura_hamu", type: "x" },
    communities: [],
    comment: "知識の共有が活発",
  },
  {
    id: 32,
    name: "repunit11",
    avatar: "../assets/staff_img/32.jpg",
    sns: { url: "https://x.com/repunit11", type: "x" },
    communities: [],
    comment: "",
  },
  {
    id: 33,
    name: "satoken",
    avatar: "../assets/staff_img/33.jpg",
    sns: { url: "https://x.com/ken5owata", type: "x" },
    communities: ["TinyGo Keeb", "秘密結社オープンフォース", "低レベル勉強会"],
    comment: "",
  },
  {
    id: 34,
    name: "n9te9",
    avatar: "../assets/staff_img/34.png",
    sns: { url: "https://x.com/n9te9", type: "x" },
    communities: [],
    comment: "",
  },
  {
    id: 35,
    name: "りくと",
    avatar: "../assets/staff_img/35.png",
    sns: { url: "https://x.com/rikut0904", type: "x" },
    communities: ["Biwako.go", "Kanazawa.go"],
    comment: "雰囲気がゆったりとしていて居心地がいいところ",
  },
  {
    id: 36,
    name: "Senou",
    avatar: "../assets/staff_img/36.jpg",
    sns: { url: "senoue", type: "" },
    communities: ["Snndai.go"],
    comment: "活発",
  },
  {
    id: 37,
    name: "takemio",
    avatar: "../assets/staff_img/37.jpg",
    sns: { url: "https://twitter.com/takemioIO/", type: "x" },
    communities: [],
    comment: "敷居の低さ！",
  },
  {
    id: 38,
    name: "sivchari",
    avatar: "../assets/staff_img/38.jpg",
    sns: { url: "https://x.com/sivchari", type: "x" },
    communities: ["株式会社LayerX, Go Conferenceメインオーガナイザー, golang.tokyoメインオーガナイザー"],
    comment: "人の温かさ、言語をいろいろな形で盛り上げる人の良さ",
  },
  {
    id: 39,
    name: "OJI",
    avatar: "../assets/staff_img/39.jpg",
    sns: { url: "https://x.com/OldBigBuddha", type: "x" },
    communities: [],
    comment: "",
  },
  {
    id: 40,
    name: "きしだ",
    avatar: "../assets/staff_img/40.png",
    sns: { url: "https://x.com/mwudo", type: "x" },
    communities: ["株式会社IVRy"],
    comment: "",
  },
  {
    id: 41,
    name: "turbofish",
    avatar: "../assets/staff_img/41.jpg",
    sns: { url: "https://x.com/turbofish_", type: "x" },
    communities: ["NOT A HOTEL"],
    comment: "多様な人が気兼ねなく楽しめる気軽さ＆寛容さ",
  },
  {
    id: 42,
    name: "kyo",
    avatar: "../assets/staff_img/42.jpg",
    sns: { url: "https://x.com/Keyl0ve_", type: "x" },
    communities: ["https://x.com/Keyl0ve_"],
    comment: "Gopher がかわいいので、だいたいのことが許される",
  },
  {
    id: 43,
    name: "micchie",
    avatar: "../assets/staff_img/43.jpg",
    sns: { url: "https://x.com/micchiebear", type: "x" },
    communities: ["一般社団法人Gophers Japan", "Mercari, Inc."],
    comment: "元気がよろしい！",
  },
  {
    id: 44,
    name: "くりち",
    avatar: "../assets/staff_img/44.jpg",
    sns: { url: "https://x.com/kurichi97", type: "x" },
    communities: ["DeckHub株式会社"],
    comment: "",
  },
  {
    id: 45,
    name: "momi",
    avatar: "../assets/staff_img/45.jpg",
    sns: { url: "https://x.com/irdx_m", type: "x" },
    communities: [],
    comment: "多様な人を受け入れる寛容さと対等に関われる心地良さ🏝️",
  },
  {
    id: 46,
    name: "budougumi0617",
    avatar: "../assets/staff_img/46.png",
    sns: { url: "https://x.com/budougumi0617", type: "x" },
    communities: ["株式会社LayerX"],
    comment: "",
  },
  {
    id: 47,
    name: "tak",
    avatar: "../assets/staff_img/47.jpg",
    sns: { url: "https://x.com/tak848_", type: "x" },
    communities: ["株式会社LayerX"],
    comment: "皆Goの推しポイントを語れる",
  },
  {
    id: 48,
    name: "Mikuto",
    avatar: "../assets/staff_img/48.jpg",
    sns: { url: "https://x.com/Mikuto_0831", type: "x" },
    communities: ["東京工科大学"],
    comment: "",
  },
  {
    id: 49,
    name: "syamasaw",
    avatar: "../assets/staff_img/49.jpg",
    sns: { url: "", type: "" },
    communities: [],
    comment: "",
  },
];
